name: xQc-Paper
version: 1.0.0
author: Adeithe
main: gg.xqc.paper.PaperPlugin
api-version: 1.13
depend: [xQc-Core,WorldEdit,WorldGuard]

commands:
  events:
    description: Manage the random event arena.
    usage: /events